// ============================================================
//  La Bàn Đầu Tư — Toàn bộ chuỗi giao diện (tiếng Việt duy nhất)
//  KHÔNG có bộ i18n zh/en. Mọi text hiển thị nằm ở đây.
//  → Rò rỉ ngôn ngữ là bất khả thi về mặt cấu trúc.
// ============================================================

export const VI = {
  app: {
    name: 'La Bàn Đầu Tư',
    short: 'La Bàn',
    tagline: 'Hỗ trợ thông tin đầu tư bằng AI',
  },

  nav: {
    market: 'Tổng Quan',
    gold: 'Vàng',
    petrol: 'Xăng Dầu',
    savings: 'Tiết Kiệm',
    bond: 'Trái Phiếu',
    profile: 'Tư Vấn Đầu Tư',
    home: 'Phân Tích Cổ Phiếu',
    // Nhãn nhóm điều hướng (sidebar)
    groupMarket: 'Thị trường',
    groupAnalysis: 'Phân tích & Tư vấn',
    groupPortfolio: 'Đầu tư của tôi',
    groupSystem: 'Hệ thống',
    chat: 'Trợ Lý AI',
    portfolio: 'Danh Mục',
    signals: 'Tín Hiệu',
    backtest: 'Đánh Giá',
    screening: 'Lọc Cổ Phiếu',
    alerts: 'Cảnh Báo',
    usage: 'Sử Dụng',
    settings: 'Cài Đặt',
    logout: 'Đăng Xuất',
    theme: 'Giao diện',
    themeLight: 'Sáng',
    themeDark: 'Tối',
  },

  common: {
    analyze: 'Phân tích',
    reanalyze: 'Phân tích lại',
    search: 'Tìm kiếm',
    loading: 'Đang tải...',
    save: 'Lưu',
    cancel: 'Huỷ',
    delete: 'Xoá',
    confirm: 'Xác nhận',
    close: 'Đóng',
    retry: 'Thử lại',
    refresh: 'Làm mới',
    edit: 'Sửa',
    add: 'Thêm',
    remove: 'Bỏ',
    viewDetails: 'Xem chi tiết',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    noData: 'Chưa có dữ liệu',
    empty: 'Trống',
    all: 'Tất cả',
    open: 'Mở',
    back: 'Quay lại',
    next: 'Tiếp',
    prev: 'Trước',
    page: 'Trang',
    total: 'Tổng',
    yes: 'Có',
    no: 'Không',
    up: 'Tăng',
    down: 'Giảm',
    flat: 'Tham chiếu',
  },

  home: {
    title: 'Phân tích cổ phiếu',
    searchPlaceholder: 'Nhập mã hoặc tên cổ phiếu, ví dụ VCB, Vinamilk, FPT',
    analyzeBtn: 'Phân tích',
    marketReviewBtn: 'Diễn biến thị trường',
    sendNotify: 'Gửi thông báo',
    fullReport: 'Báo cáo đầy đủ',
    historyTrend: 'Xu hướng lịch sử',
    rerunMarketReview: 'Chạy lại diễn biến thị trường',
    stocks: 'Cổ phiếu',
    selectAll: 'Chọn tất cả',
    keyInsights: 'Nhận định chính',
    actionAdvice: 'Khuyến nghị hành động',
    trendPrediction: 'Dự báo xu hướng',
    marketSentiment: 'Tâm lý thị trường',
    strategyPoints: 'Mốc chiến lược',
    idealBuy: 'Điểm mua lý tưởng',
    secondaryBuy: 'Điểm mua bổ sung',
    stopLoss: 'Cắt lỗ',
    takeProfit: 'Chốt lời',
    relatedBoards: 'Nhóm ngành liên quan',
    news: 'Tin tức',
    emptyAnalysis: 'Nhập một mã cổ phiếu để bắt đầu phân tích.',
  },

  chat: {
    title: 'Trợ lý AI',
    placeholder: 'Hỏi về cổ phiếu, vàng, lãi suất, kế hoạch đầu tư...',
    send: 'Gửi',
    newChat: 'Cuộc trò chuyện mới',
    sessions: 'Lịch sử trò chuyện',
    thinking: 'Đang suy nghĩ...',
    emptyState: 'Hỏi trợ lý AI về cổ phiếu, vàng, lãi suất hay kế hoạch đầu tư của bạn.',
  },

  portfolio: {
    title: 'Danh mục đầu tư',
    account: 'Tài khoản',
    addAccount: 'Thêm tài khoản',
    holdings: 'Cổ phiếu nắm giữ',
    symbol: 'Mã',
    quantity: 'Số lượng',
    avgPrice: 'Giá vốn',
    marketPrice: 'Giá thị trường',
    marketValue: 'Giá trị',
    pnl: 'Lãi/Lỗ',
    weight: 'Tỷ trọng',
    risk: 'Phân tích rủi ro',
    trades: 'Giao dịch',
    emptyState: 'Chưa có tài khoản. Hãy tạo một tài khoản để theo dõi danh mục.',
    // Tài sản khác (vàng / tiết kiệm / trái phiếu) + phân bổ tài sản.
    otherAssets: 'Tài sản khác',
    otherAssetsHint: 'Vàng, tiết kiệm, trái phiếu — theo dõi theo giá trị hiện tại (VND)',
    addOtherAsset: 'Thêm tài sản',
    assetClass: 'Loại tài sản',
    assetLabel: 'Tên tài sản',
    assetValue: 'Giá trị (VND)',
    interestRate: 'Lãi suất (%/năm)',
    maturityDate: 'Ngày đáo hạn',
    classVang: 'Vàng',
    classTietKiem: 'Tiết kiệm',
    classTraiPhieu: 'Trái phiếu',
    classCoPhieu: 'Cổ phiếu',
    classTienMat: 'Tiền mặt',
    allocationTitle: 'Phân bổ tài sản',
    allocationHint: 'Cơ cấu toàn bộ tài sản trong tài khoản theo giá trị.',
    totalNetWorth: 'Tổng tài sản ròng',
    noOtherAssets: 'Chưa có tài sản khác. Thêm vàng, tiết kiệm hoặc trái phiếu để theo dõi đầy đủ.',
    deleteAsset: 'Xoá tài sản',
    assetAdded: 'Đã thêm tài sản',
    assetDeleted: 'Đã xoá tài sản',
  },

  signals: {
    title: 'Tín hiệu AI',
    action: 'Hành động',
    confidence: 'Độ tin cậy',
    score: 'Điểm',
    horizon: 'Khung thời gian',
    entry: 'Vùng mua',
    stopLoss: 'Cắt lỗ',
    target: 'Mục tiêu',
    risk: 'Rủi ro',
    catalyst: 'Chất xúc tác',
    status: 'Trạng thái',
    emptyState: 'Chưa có tín hiệu. Tín hiệu tự động xuất hiện sau khi phân tích một cổ phiếu và có khuyến nghị rõ ràng (Mua, Bán, Quan sát…). Hãy phân tích thêm cổ phiếu để tạo tín hiệu.',
  },

  backtest: {
    title: 'Đánh giá dự báo',
    subtitle: 'Đo độ chính xác của dự báo AI so với giá thực tế',
    run: 'Chạy đánh giá',
    results: 'Kết quả',
    accuracy: 'Độ chính xác',
    window: 'Cửa sổ đánh giá (ngày)',
    emptyState: 'Chạy đánh giá để xem độ chính xác của các dự báo trước đây.',
  },

  alerts: {
    title: 'Cảnh báo',
    rules: 'Quy tắc cảnh báo',
    addRule: 'Thêm quy tắc',
    triggers: 'Lịch sử kích hoạt',
    type: 'Loại',
    target: 'Đối tượng',
    severity: 'Mức độ',
    enabled: 'Bật',
    emptyState: 'Chưa có quy tắc cảnh báo nào.',
  },

  market: {
    title: 'Tổng quan thị trường',
    subtitle: 'Toàn cảnh đầu tư hôm nay — cổ phiếu, vàng, xăng dầu, lãi suất',
    multiAsset: 'Các kênh đầu tư khác',
    indices: 'Chỉ số chính',
    breadth: 'Độ rộng thị trường',
    advancers: 'Tăng',
    decliners: 'Giảm',
    unchanged: 'Tham chiếu',
    topGainers: 'Tăng mạnh nhất',
    topLosers: 'Giảm mạnh nhất',
    sectors: 'Nhóm ngành',
    sectorsNote: 'Bình quân theo rổ VN30',
    totalValue: 'Tổng giá trị khớp',
    universeNote: 'Top tăng/giảm và độ rộng tính trong rổ VN30',
    updated: 'Cập nhật',
    empty: 'Chưa lấy được dữ liệu thị trường. Hãy thử lại sau.',
  },

  gold: {
    title: 'Vàng',
    subtitle: 'Giá vàng SJC, giá thế giới và chênh lệch (premium) so với giá quy đổi',
    updated: 'Cập nhật',
    empty: 'Chưa lấy được dữ liệu vàng. Hãy thử lại sau.',
    premiumLabel: 'Chênh lệch SJC so với thế giới',
    sjc: 'Vàng miếng SJC',
    buy: 'Mua vào',
    sell: 'Bán ra',
    spread: 'Chênh lệch mua–bán',
    perLuongNote: 'Đơn vị: VND/lượng (1 lượng = 37,5 g)',
    world: 'Vàng thế giới',
    worldOz: 'Giá thế giới',
    worldPerLuong: 'Quy đổi VND/lượng',
    source: 'Nguồn',
    fx: 'Tỷ giá',
    fxNote: 'Giá USD bán ra của Vietcombank',
    howLabel: 'Cách tính chênh lệch',
    howBody:
      'Giá thế giới yết theo troy ounce (31,1 g), giá trong nước theo lượng (37,5 g) — ' +
      'nên phải quy đổi cả đơn vị (×1,20565) lẫn tỷ giá USD/VND. Chênh lệch cao chủ yếu ' +
      'do hạn chế nguồn cung vàng miếng theo Nghị định 24.',
    chartLabel: 'Lịch sử giá vàng (VND/lượng)',
    chartNote: 'SJC trong nước vs thế giới quy đổi',
    chartLoading: 'Đang tải lịch sử giá...',
    premiumBand: 'Chênh lệch trung bình kỳ',
    lineSjc: 'SJC trong nước',
    lineWorld: 'Thế giới quy đổi',
    typesLabel: 'Giá các loại vàng trong nước',
    typeName: 'Loại vàng',
    typesNote: 'Nguồn: BTMC · quy đổi VND/lượng · "--" là loại chỉ niêm yết giá mua.',
  },

  petrol: {
    title: 'Xăng Dầu',
    subtitle: 'Giá bán lẻ trong nước theo kỳ điều hành và dầu thô thế giới',
    empty: 'Chưa lấy được dữ liệu xăng dầu. Hãy thử lại sau.',
    discontinued: 'Đã chuyển sang E10',
    cycleLabel: 'Kỳ điều hành',
    effective: 'Giá hiệu lực từ',
    nextAdj: 'Kỳ điều hành kế',
    world: 'Dầu thô thế giới',
    chartLabel: 'Lịch sử giá xăng dầu',
    chartLoading: 'Đang tải lịch sử giá...',
    chartNote: 'Trục trái: giá xăng VN (đồng/lít) · trục phải: dầu Brent (USD/thùng, nét đứt).',
    lineE5: 'E5 RON 92',
    lineRon95: 'RON 95-III',
    lineBrent: 'Brent (thế giới)',
    mechLabel: 'Vì sao giá xăng VN khác giá dầu thế giới',
  },

  savings: {
    title: 'Tiết Kiệm',
    subtitle: 'Lãi suất gửi tiết kiệm theo ngân hàng và kỳ hạn',
    empty: 'Chưa lấy được dữ liệu lãi suất. Hãy thử lại sau.',
    bestLabel: 'Lãi suất tốt nhất theo kỳ hạn',
    tableLabel: 'Bảng lãi suất theo ngân hàng',
    bank: 'Ngân hàng',
    sbvLabel: 'Lãi suất điều hành SBV',
  },

  bond: {
    title: 'Trái phiếu & lãi suất điều hành',
    subtitle: 'So sánh mặt bằng lãi suất: SBV, Fed và lợi suất trái phiếu',
    empty: 'Chưa lấy được dữ liệu lãi suất. Hãy thử lại sau.',
    sbv: 'Lãi suất điều hành SBV',
    sbvSub: 'Tái cấp vốn · từ 6/2023',
    fed: 'Lãi suất Fed',
    fedSub: 'Khung mục tiêu · 6/2026',
    us10y: 'Trái phiếu Mỹ 10 năm',
    us10ySub: 'Live · yfinance',
    vn10y: 'Trái phiếu CP VN 10 năm',
    vn10ySub: 'Chưa có nguồn live miễn phí',
    refBadge: 'tham khảo',
    spreadLabel: 'Chênh lệch',
    spreadSbvFed: 'SBV − Fed (trung điểm)',
    spreadVnUs: 'VN10Y − US10Y',
    chartLabel: 'Lợi suất trái phiếu Mỹ 10 năm (1 năm)',
    chartLoading: 'Đang tải lịch sử...',
    noteLabel: 'Ghi chú',
  },

  profile: {
    title: 'Hồ sơ rủi ro & Gợi ý đầu tư',
    subtitle: 'Trả lời bảng hỏi để xác định khẩu vị rủi ro và nhận gợi ý phân bổ theo nghiệp vụ',
    // Nhãn các trường form.
    hoTen: 'Họ và tên',
    hoTenPlaceholder: 'Nhập họ và tên',
    ngaySinh: 'Ngày sinh',
    diaChi: 'Địa chỉ',
    diaChiPlaceholder: 'Nhập địa chỉ',
    loaiCongTy: 'Loại công ty đầu tư',
    loaiCongTyPlaceholder: 'Chọn loại công ty đầu tư',
    thoiGian: 'Thời gian đầu tư',
    thoiGianPlaceholder: 'Chọn thời gian đầu tư',
    mucTieu: 'Mục tiêu đầu tư',
    mucTieuPlaceholder: 'Chọn mục tiêu đầu tư',
    kinhNghiem: 'Kinh nghiệm đầu tư',
    kinhNghiemPlaceholder: 'Chọn kinh nghiệm đầu tư',
    ruiRo: 'Mức rủi ro chấp nhận được',
    ruiRoPlaceholder: 'Chọn mức rủi ro chấp nhận được',
    loiNhuan: 'Lợi nhuận mong muốn',
    loiNhuanPlaceholder: 'Chọn lợi nhuận mong muốn',
    required: 'Bắt buộc',
    selectPlaceholder: '— Chọn —',
    // Nút + trạng thái.
    submit: 'Gợi ý đầu tư',
    submitting: 'Đang tính toán...',
    reset: 'Nhập lại',
    formInfo: 'Thông tin cá nhân',
    formSurvey: 'Bảng hỏi khẩu vị',
    // Kết quả.
    resultTitle: 'Kết quả gợi ý',
    totalScore: 'Tổng điểm',
    riskGroup: 'Nhóm khẩu vị',
    forcedNote: 'Bạn chọn mức chịu lỗ "Dưới 5%" → theo nguyên tắc thận trọng, hệ thống ép về nhóm Phòng thủ bất kể tổng điểm.',
    allocationTitle: 'Phân bổ theo mức biến động cổ phiếu',
    allocationHint: 'Tỷ lệ gợi ý giữa 3 nhóm cổ phiếu (đo bằng biên độ giá 1 năm).',
    suggestStocksTitle: 'Cổ phiếu đề xuất theo ngành',
    volatilityCol: 'Biến động 1 năm',
    bucketOnDinh: 'Ổn định',
    bucketTrungBinh: 'Trung bình',
    bucketRuiRo: 'Rủi ro',
    bucketOnDinhHint: 'Biên độ < 30% · giá chạy êm',
    bucketTrungBinhHint: 'Biên độ 30–60% · sóng theo chu kỳ',
    bucketRuiRoHint: 'Biên độ > 60% · dao động mạnh',
    methodTitle: 'Cách tính (theo tài liệu nghiệp vụ)',
    methodBody: 'Cộng điểm 5 trường (Mục tiêu, Thời gian, Kinh nghiệm, Lợi nhuận, Mức rủi ro) ra tổng 5–18 điểm. 5–9: Phòng thủ (70-20-10) · 10–14: Cân bằng (40-40-20) · 15–18: Tấn công (10-30-60). Cổ phiếu phân loại theo biên độ giá 252 phiên: (đỉnh − đáy)/đáy.',
    emptyResult: 'Điền đủ thông tin bắt buộc rồi bấm "Gợi ý đầu tư".',
    error: 'Không tính được gợi ý. Hãy thử lại sau.',
  },

  usage: {
    title: 'Sử dụng AI',
    today: 'Hôm nay',
    month: 'Tháng này',
    allTime: 'Tất cả',
    totalCalls: 'Tổng lượt gọi',
    totalTokens: 'Tổng token',
    byModel: 'Theo mô hình',
    byCallType: 'Theo loại tác vụ',
    recentCalls: 'Lượt gọi gần đây',
  },

  settings: {
    title: 'Cài đặt',
    subtitle: 'Thiết lập La Bàn Đầu Tư theo ý bạn — gọn gàng, dễ hiểu',
    save: 'Lưu thay đổi',
    saving: 'Đang lưu…',
    saved: 'Đã lưu',
    savedAt: 'Đã lưu lúc',
    reload: 'Tải lại',
    noChanges: 'Không có thay đổi nào để lưu.',
    loadError: 'Không thể tải cấu hình. Hãy kiểm tra kết nối máy chủ và thử lại.',
    conflict: 'Cấu hình vừa bị thay đổi ở nơi khác. Hãy tải lại trang rồi lưu lại.',
    invalid: 'Một vài ô chưa hợp lệ, hãy kiểm tra lại.',
    saveFailed: 'Lưu cấu hình thất bại. Hãy thử lại.',
    changes: 'thay đổi',
    required: 'bắt buộc',
    advanced: 'Tùy chọn nâng cao',
    showAdvanced: 'Hiện tùy chọn nâng cao',
    hideAdvanced: 'Ẩn tùy chọn nâng cao',
    version: 'Phiên bản cấu hình',
    footerNote: 'Các cấu hình kỹ thuật khác (proxy, cơ sở dữ liệu, Docker…) có thể chỉnh trực tiếp trong file .env.',
    // Lịch tự động
    runNow: 'Chạy ngay',
    running: 'Đang chạy…',
    ranNow: 'Đã bắt đầu chạy phân tích. Kết quả sẽ tới qua kênh thông báo.',
    runFailed: 'Không thể bắt đầu chạy. Hãy thử lại.',
    schedStatusOn: 'Đang bật',
    schedStatusOff: 'Đang tắt',
    schedRunning: 'Đang chạy',
    schedNextRun: 'Lần chạy kế',
    schedLastRun: 'Lần chạy gần nhất',
    schedNever: 'chưa có',
    // Gửi thử thông báo
    testSend: 'Gửi thử',
    testing: 'Đang gửi…',
    testOk: 'Đã gửi tin nhắn thử thành công!',
    testFail: 'Gửi thử thất bại. Hãy kiểm tra lại thông tin.',
    testMissing: 'Hãy điền thông tin Telegram/Email trước khi gửi thử.',
    // Gợi ý liên kết
    alertRulesHint: 'Thêm và chỉnh các quy tắc cảnh báo (giá, RSI, MACD…) tại trang',
    alertRulesLink: 'Cảnh Báo',
  },

  auth: {
    login: 'Đăng nhập',
    password: 'Mật khẩu',
    passwordConfirm: 'Xác nhận mật khẩu',
    loginBtn: 'Đăng nhập',
    wrongPassword: 'Mật khẩu không đúng',
    setupTitle: 'Thiết lập lần đầu',
  },

  errors: {
    generic: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    network: 'Mất kết nối tới máy chủ.',
    notFound: 'Không tìm thấy.',
    marketReviewInProgress: 'Diễn biến thị trường đang chạy, vui lòng thử lại sau.',
    provideFileOrText: 'Vui lòng cung cấp tệp hoặc dán văn bản.',
    invalidStockCode: 'Vui lòng nhập mã hoặc tên cổ phiếu hợp lệ.',
  },

  toast: {
    analysisQueued: 'Đã đưa vào hàng đợi phân tích',
    analysisDone: 'Phân tích hoàn tất',
    marketReviewQueued: 'Đã gửi tác vụ diễn biến thị trường',
    saved: 'Đã lưu',
    deleted: 'Đã xoá',
    copied: 'Đã sao chép',
  },

  notFound: {
    title: 'Không tìm thấy trang',
    backHome: 'Về trang chủ',
  },
} as const

/** Thay tham số trong chuỗi mẫu: vif('Tổng {n} kết quả', { n: 5 }). */
export const vif = (template: string, vars: Record<string, string | number>): string =>
  template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''))

export type ViStrings = typeof VI
